executed with-ccu and split up py2 and py3 handling to avoid overload

diff --git a/Makefile.org b/Makefile.org
--- a/Makefile.org
+++ b/Makefile.org
@@ -1,11 +1,11 @@
-VERSION            = 0.6.1
+VERSION            = 0.6
 REPO_PATH         ?= $(shell pwd)
-CHROOT_PATH       ?= $(shell pwd)/buildroot
+CHROOT_PATH       ?= $(shell pwd)/chroot
 CHROOT_DEB_MIRROR ?= http://ftp.de.debian.org/debian
 CCU_PREDIST_PATH  ?= $(shell pwd)/ccu_pkg
 DIST_PATH         ?= $(shell pwd)/dist
 CCU_PKG_PATH      ?= $(DIST_PATH)/ccu
-CCU_HOST          ?= ccu3-webui
+CCU_HOST          ?= ccu
 
 # On OS X with macports coverage has no "coverage" link
 COVERAGE2 := $(shell if which coverage2 >/dev/null 2>&1; then echo coverage2; \
@@ -15,14 +15,15 @@ COVERAGE2 := $(shell if which coverage2 >/dev/null 2>&1; then echo coverage2; \
 COVERAGE3 := $(shell if which coverage3 >/dev/null 2>&1; then echo coverage3; \
 		   elif which coverage-3.4 >/dev/null 2>&1; then echo coverage-3.4; fi)
 
-.PHONY: dist
-
+.PHONY: chroot dist
 
 help:
 	@echo
 	@echo "Available commands:"
 	@echo
 	@echo "setup              - Install packages needed for development (at least on debian)"
+	@echo "chroot             - Create a debian chroot which is used to get python files for"
+	@echo "                     making python available to the CCU later"
 	@echo "version            - Set a new version number"
 	@echo
 	@echo "dist		  - Create all release packages"
@@ -48,20 +49,17 @@ help:
 	@echo "install-ccu-python - Install python files from chroot on CCU via SSH"
 	@echo "install-ccu-pmatic - Install pmatic files on CCU via SSH"
 	@echo
-	@echo
-	@echo "run	          - run pmatic directly from command line"
-	@echo
 	@echo "clean	          - Cleanup development files (e.g. chroot)"
 	@echo
 
 setup:
 	sudo apt-get install debootstrap qemu-user-static rsync dialog python-pytest python-pip \
 			python3-pip python-sphinx snakefood python-lxml \
-			python-six 
+			python-six
 	sudo pip install --upgrade pytest_flakes pytest_runner coverage beautifulsoup4 \
-			 Pygments==2.5.2 requests cryptography
+			sphinxcontrib-images twine requests
 	sudo pip3 install --upgrade pytest_flakes pytest_runner coverage beautifulsoup4 \
-			 sphinxcontrib-images requests cryptography
+			requests
 	# port install py-coverage py34-coverage \
 	# 	       py-setuptools py34-setuptools \
 	# 	       py-pytest py34-pytest
@@ -77,102 +75,66 @@ dist: dist-os dist-ccu
 
 dist-os:
 	[ ! -d $(DIST_PATH) ] && mkdir $(DIST_PATH) || true
-	python3 setup.py sdist
+	python setup.py sdist
 	@echo "Created dist/pmatic-$(VERSION).tar.gz"
 
+chroot:
+	[ ! -d $(CHROOT_PATH) ] && mkdir $(CHROOT_PATH) || true
+	sudo debootstrap --foreign --arch=armel \
+	    --include=python,python-pip \
+	    wheezy $(CHROOT_PATH) $(CHROOT_DEB_MIRROR)
+	sudo cp /usr/bin/qemu-arm-static $(CHROOT_PATH)/usr/bin
+	LANG=C sudo chroot $(CHROOT_PATH) /bin/bash -c "/debootstrap/debootstrap --second-stage"
+	LANG=C sudo chroot $(CHROOT_PATH) /bin/bash -c \
+	    "pip install --install-option=\"--prefix=/usr\" simpleTR64"
+	LANG=C sudo chroot $(CHROOT_PATH) /bin/bash -c \
+	    "pip install --install-option=\"--prefix=/usr\" pytz"
+
 dist-ccu:
-	sudo $(MAKE) dist-ccu-step1a
-	sudo $(MAKE) dist-ccu-step1b
-	$(MAKE) dist-ccu-step2a
-	$(MAKE) dist-ccu-step2b
+	sudo $(MAKE) dist-ccu-step1
+	$(MAKE) dist-ccu-step2
 
-dist-ccu-step1: dist-ccu-step1a dist-ccu-step1b
-
-dist-ccu-step1a:
+dist-ccu-step1:
+	@if ! ls $(CHROOT_PATH)/* >/dev/null 2>&1; then \
+	    echo "ERROR: chroot missing. Please run \"make chroot\", then try again." ; \
+	    exit 1 ; \
+	fi
 	mkdir -p $(CCU_PREDIST_PATH)/python
 	cd $(CHROOT_PATH)/usr ; \
 	rsync -aRvL --no-g $$(cat $(REPO_PATH)/ccu_pkg/python-modules.list) \
 	    $(CCU_PREDIST_PATH)/python ; \
 	rsync -aRL --no-g $$(cat $(REPO_PATH)/ccu_pkg/python-modules-optional.list) \
 	    $(CCU_PREDIST_PATH)/python 2>/dev/null || true
-	rsync -av --no-g $(CHROOT_PATH)/lib/arm-linux-gnueabi/libexpat.so.1 \
-	    $(CCU_PREDIST_PATH)/python/lib/
+	rsync -av --no-g $(CHROOT_PATH)/lib/arm-linux-gnueabi/libexpat.so.1.* \
+	    $(CCU_PREDIST_PATH)/libs/
 	# Cleanup site-packages to dist-packages
 	rsync -av $(CCU_PREDIST_PATH)/python/lib/python2.7/site-packages/* \
 	    $(CCU_PREDIST_PATH)/python/lib/python2.7/dist-packages/
 	rm -rf $(CCU_PREDIST_PATH)/python/lib/python2.7/site-packages
 
-dist-ccu-step1b:
-	mkdir -p $(CCU_PREDIST_PATH)_py3/python
-	cd $(CHROOT_PATH)/usr ; \
-	rsync -aRvL --no-g $$(cat $(CCU_PREDIST_PATH)_py3/python-modules.list) \
-	    $(CCU_PREDIST_PATH)_py3/python ; \
-	rsync -aRL --no-g $$(cat $(CCU_PREDIST_PATH)_py3/python-modules-optional.list) \
-	    $(CCU_PREDIST_PATH)_py3/python 2>/dev/null || true 
-	rsync -av --no-g $(CHROOT_PATH)/lib/arm-linux-gnueabi/libexpat.so.1 \
-	    $(CCU_PREDIST_PATH)_py3/python/lib/
-	# Cleanup site-packages to dist-packages
-	rsync -av $(CCU_PREDIST_PATH)_py3/python/lib/python3.7/site-packages/* \
-	    $(CCU_PREDIST_PATH)_py3/python/lib/python3.7/dist-packages/
-	rm -rf $(CCU_PREDIST_PATH)_py3/python/lib/python3.7/site-packages
-
-dist-ccu-step2: dist-ccu-step2a dist-ccu-step2b
-
-dist-ccu-step2a:
+dist-ccu-step2:
 	[ ! -d $(DIST_PATH) ] && mkdir $(DIST_PATH) || true
-	[ ! -d $(CCU_PKG_PATH) ] && mkdir $(CCU_PKG_PATH) || true
-	[ ! -d $(CCU_PKG_PATH)/python ] && mkdir $(CCU_PKG_PATH)/python || true
-	[ ! -d $(CCU_PKG_PATH)/python/bin ] && mkdir $(CCU_PKG_PATH)/python/bin || true
-	[ ! -d $(CCU_PKG_PATH)/python/lib ] && mkdir $(CCU_PKG_PATH)/python/lib || true
-	rsync -av $(CCU_PREDIST_PATH)/python/bin $(CCU_PREDIST_PATH)/python/lib $(CCU_PKG_PATH)/python
+	rsync -av $(CCU_PREDIST_PATH)/python $(CCU_PREDIST_PATH)/libs $(CCU_PKG_PATH)/
 	rsync -aRv --no-g \
 	    --exclude=\*.pyc \
 	    --exclude=.\*.swp \
 	    --exclude=__pycache__ \
 	    pmatic examples pmatic-manager manager_static \
 	    $(CCU_PKG_PATH)
-	cd $(CCU_PKG_PATH)/python/lib/python2.7 ; python -m compileall .
-	tar -cv -C $(CCU_PKG_PATH) -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_2.7.tar .
+	cd $(CCU_PKG_PATH) ; python -m compileall .
+	tar -cv -C $(CCU_PKG_PATH) -f $(DIST_PATH)/pmatic-$(VERSION)_ccu.tar .
 	[ -d $(CCU_PKG_PATH) ] && rm -rf $(CCU_PKG_PATH) || true
-	tar -rv -C ccu_pkg -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_2.7.tar \
+	tar -rv -C ccu_pkg -f $(DIST_PATH)/pmatic-$(VERSION)_ccu.tar \
 	    update_script \
 	    python-wrapper \
 	    pmatic.init
-	tar -rv -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_2.7.tar \
+	tar -rv -f $(DIST_PATH)/pmatic-$(VERSION)_ccu.tar \
 	    LICENSE \
 	    README.rst
-	tar -rv -C pmatic.egg-info -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_2.7.tar \
+	tar -rv -C pmatic.egg-info -f $(DIST_PATH)/pmatic-$(VERSION)_ccu.tar \
 	    PKG-INFO
-	gzip -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_2.7.tar
-	@echo "Created dist/pmatic-$(VERSION)_ccu.tar_2.7.gz"
-
-dist-ccu-step2b:
-	[ ! -d $(DIST_PATH) ] && mkdir $(DIST_PATH) || true
-	[ ! -d $(CCU_PKG_PATH) ] && mkdir $(CCU_PKG_PATH) || true
-	[ ! -d $(CCU_PKG_PATH)/python ] && mkdir $(CCU_PKG_PATH)/python || true
-	[ ! -d $(CCU_PKG_PATH)/python/bin ] && mkdir $(CCU_PKG_PATH)/python/bin || true
-	[ ! -d $(CCU_PKG_PATH)/python/lib ] && mkdir $(CCU_PKG_PATH)/python/lib || true
-	rsync -av $(CCU_PREDIST_PATH)_py3/python/bin $(CCU_PREDIST_PATH)_py3/python/lib $(CCU_PKG_PATH)/python
-	rsync -aRv --no-g \
-	    --exclude=\*.pyc \
-	    --exclude=.\*.swp \
-	    --exclude=__pycache__ \
-	    pmatic examples pmatic-manager manager_static \
-	    $(CCU_PKG_PATH)
-	cd $(CCU_PKG_PATH)/python/lib/python3.7 ; python3 -m compileall .
-	tar -cv -C $(CCU_PKG_PATH) -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_3.7.tar .
-	[ -d $(CCU_PKG_PATH) ] && rm -rf $(CCU_PKG_PATH) || true
-	tar -rv -C ccu_pkg_py3 -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_3.7.tar \
-	    update_script \
-	    python-wrapper \
-	    pmatic.init
-	tar -rv -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_3.7.tar \
-	    LICENSE \
-	    README.rst
-	tar -rv -C pmatic.egg-info -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_3.7.tar \
-	    PKG-INFO
-	gzip -f $(DIST_PATH)/pmatic-$(VERSION)_ccu_3.7.tar
-	@echo "Created dist/pmatic-$(VERSION)_ccu.tar_3.7.gz"
+	gzip -f $(DIST_PATH)/pmatic-$(VERSION)_ccu.tar
+	@echo "Created dist/pmatic-$(VERSION)_ccu.tar.gz"
 
 test:
 	@if [ -z "$(COVERAGE2)" ]; then \
@@ -193,10 +155,6 @@ test-python3:
 test-with-ccu:
 	TEST_WITH_CCU=1 $(MAKE) test
 
-test-with-ccu-py3:
-	TEST_WITH_CCU=1 $(COVERAGE3) run -a --include='pmatic/*' --source=pmatic setup.py test
-	TEST_WITH_CCU=1 $(MAKE) coverage coverage-html
-
 coverage:
 	$(COVERAGE2) report
 
@@ -212,23 +170,14 @@ install:
 install-ccu: install-ccu-python install-ccu-pmatic install-ccu-scripts
 
 install-ccu-python:
-	ssh root@$(CCU_HOST) "[ -d /usr/local/etc/config/addons/pmatic ] || mkdir /usr/local/etc/config/addons/pmatic"
-	ssh root@$(CCU_HOST) "[ -d /usr/local/etc/config/addons/pmatic/python ] || mkdir /usr/local/etc/config/addons/pmatic/python"
 	rsync -av --no-g \
 	    --exclude=\*.pyc \
 	    --exclude=.\*.swp \
 	    --exclude=__pycache__ \
 	    $(CCU_PREDIST_PATH)/python/* \
 	    root@$(CCU_HOST):/usr/local/etc/config/addons/pmatic/python/
-	rsync -av --no-g \
-	    --exclude=\*.pyc \
-	    --exclude=.\*.swp \
-	    --exclude=__pycache__ \
-	    $(CCU_PREDIST_PATH)/python3/* \
-	    root@$(CCU_HOST):/usr/local/etc/config/addons/pmatic/python/
 
 install-ccu-pmatic:
-	ssh root@$(CCU_HOST) "[ -d /usr/local/etc/config/addons/pmatic/etc ] || mkdir /usr/local/etc/config/addons/pmatic/etc"
 	rsync -aRv --no-g \
 	    --exclude=\*.pyc \
 	    --exclude=.\*.swp \
@@ -239,20 +188,8 @@ install-ccu-pmatic:
 	    --exclude=\*.pyc \
 	    --exclude=.\*.swp \
 	    --exclude=__pycache__ \
-	    pmatic \
-	    root@$(CCU_HOST):/usr/local/etc/config/addons/pmatic/python/lib/python3.7/
-	rsync -aRv --no-g \
-	    --exclude=\*.pyc \
-	    --exclude=.\*.swp \
-	    --exclude=__pycache__ \
 	    examples \
 	    root@$(CCU_HOST):/usr/local/etc/config/addons/pmatic/scripts/
-	rsync -aRv --no-g \
-	    --exclude=\*.pyc \
-	    --exclude=.\*.swp \
-	    --exclude=__pycache__ \
-	    manager_static \
-	    root@$(CCU_HOST):/usr/local/etc/config/addons/pmatic
 	rsync -aRv --no-g \
 	    pmatic-manager \
 	    root@$(CCU_HOST):/usr/local/bin/pmatic-manager
@@ -274,35 +211,32 @@ setversion:
 	sed -i "s/version='.*',/version='$(NEW_VERSION)',/g" setup.py
 	sed -i "s/^VERSION=.*/VERSION=$(NEW_VERSION)/g" ccu_pkg/pmatic.init
 
-clean: clean-dist clean-test
+clean: clean-chroot clean-dist clean-test
 	$(MAKE) -C doc clean
 
 clean-test:
 	rm -rf tests/__pycache__ || true
-	sudo rm -rf pmatic.egg-info || true
+	rm -rf pmatic.egg-info || true
 	rm -rf *.egg || true
 	rm -rf .coverage htmlcov || true
 	rm -rf .cache || true
 
-clean-dist:
-	sudo rm -rf build 2>/dev/null || true
-	sudo rm -rf dist 2>/dev/null || true
-	sudo rm -rf $(CCU_PKG_PATH)/python 2>/dev/null || true
-	sudo rm -rf $(CCU_PKG_PATH)/python3 2>/dev/null || true
-	sudo rm -rf $(CCU_PREDIST_PATH)/python 2>/dev/null || true
-	sudo rm -rf $(CCU_PREDIST_PATH)_py3/python 2>/dev/null || true
+clean-chroot:
+	rm -rf --one-file-system $(CHROOT_PATH)
 
+clean-dist:
+	rm -rf build 2>/dev/null || true
+	rm -rf dist 2>/dev/null || true
 
 travis-build:
 	GIT_COMMIT=$(shell git rev-parse --short HEAD) ; \
 	NEW_VERSION=$$GIT_COMMIT $(MAKE) setversion ; \
-	$(MAKE) dist-os dist-ccu-step2a ; \
-	$(MAKE) dist-os dist-ccu-step2b ; \
+	$(MAKE) dist-os dist-ccu-step2 ; \
 	PKG_PATH=$(shell pwd)/dist ; \
 	cd $$HOME ; \
 	git config --global user.email "travis@travis-ci.org" ; \
 	git config --global user.name "Travis" ; \
-	git clone --quiet --branch=gh-pages https://$$GH_TOKEN@github.com/mweiss/pmatic.git gh-pages > /dev/null ; \
+	git clone --quiet --branch=gh-pages https://$$GH_TOKEN@github.com/LarsMichelsen/pmatic.git gh-pages > /dev/null ; \
 	cd gh-pages ; \
 	cp -f $$PKG_PATH/pmatic-$${GIT_COMMIT}_ccu.tar.gz pmatic-snapshot_ccu.tar.gz ; \
 	cp -f $$PKG_PATH/pmatic-$${GIT_COMMIT}.tar.gz pmatic-snapshot.tar.gz ; \
@@ -322,7 +256,3 @@ travis-doc:
 	git commit -m "Travis doc $$TRAVIS_BUILD_NUMBER pushed to gh-pages" ; \
 	git push -fq origin gh-pages > /dev/null ; \
 	echo "Finished adding current docs"
-
-run:
-	[ ! -d etc ] && mkdir etc || true; \
-	python pmatic-manager -g -o etc -e . -r examples -t ./manager_static -f etc/pmatic.log
